server:
  type: DefaultServer
  applicationConnectors:
  - type: http
    addr: :8080
  adminConnectors:
  - type: http
    addr: :8081
  requestLog:
    type: DefaultRequestLog
    appenders:
    - type: ConsoleAppender
    - type: FileAppender
      currentLogFilename: /tmp/gomelon-access.log

logging:
  level: DEBUG
  loggers:
    gomelon.server: INFO
    gomelon.configuration: WARN
  appenders:
  - type: FileAppender
    threshold: INFO
    currentLogFilename: /tmp/gomelon.log
  - type: ConsoleAppender

metrics:
  frequency: 1s
